export const GENERATION_TIMEOUT_MS = 45_000;
export const ACTIVATION_PROVIDER_CHAIN_TIMEOUT_MS =
  GENERATION_TIMEOUT_MS * 2 + 15_000;
export const CHOICE_VERIFICATION_TIMEOUT_MS =
  GENERATION_TIMEOUT_MS * 4 + 15_000;
export const ACTIVATION_GENERATION_COMPLETION_SLACK_MS = 15_000;
export const ACTIVATION_PUBLISH_TRANSACTION_MAX_WAIT_MS = 5_000;
export const ACTIVATION_PUBLISH_TRANSACTION_TIMEOUT_MS = 30_000;
export const ACTIVATION_RESERVATION_TRANSACTION_MAX_WAIT_MS = 5_000;
export const ACTIVATION_RESERVATION_TRANSACTION_TIMEOUT_MS = 15_000;
export const ACTIVATION_GENERATION_TIMEOUT_MS =
  ACTIVATION_PROVIDER_CHAIN_TIMEOUT_MS +
  CHOICE_VERIFICATION_TIMEOUT_MS +
  ACTIVATION_GENERATION_COMPLETION_SLACK_MS +
  ACTIVATION_PUBLISH_TRANSACTION_TIMEOUT_MS;
